
name: Build and Deploy
on: 
  push:
  schedule: 
    - cron: '0 0 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Get advice
      run: npm install && npm run advice

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: .

    - name: Send mail ✉️
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: 今日穿衣建议
        # Read file contents as body:
        body: file://index.html
        to: 598777720@qq.com
        from: hgwxxdd # <user@example.com>

        # Optional carbon copy recipients
        # cc: kyloren@starkiller.com,leia@alderaan.com
        # Optional blind carbon copy recipients
        # bcc: r2d2@jakku.com,hansolo@milleniumfalcon.com
        # Optional content type (defaults to text/plain):
        content_type: text/html
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true

